version: "3"
services:
   database:
       image: mysql
       environment:
           MYSQL_ROOT_PASSWORD: ibrahim
       volumes:
           - .:/var/lib/mysql
   node-app:
       build: .
       ports:
           - "8080:8080"

